### PR TITLE
Adding spark.hadoop.fs.azure properties needed  for NativeAzureFileSy…

### PR DESCRIPTION
**Pull request by andrijaperovic**
…stem to work correctly in spark context
Please see:
https://github.com/Azure/feast-azure/issues/41

### CODE REVIEW

**Comment by andrijaperovic** [comment]
Can you please take a look @jainr @snowmanmsft
++ @rramani

**Comment by jainr** [comment]
Thanks for the contribution, can you also add an else block which tells user that they need to set those params if not found?

**Comment by andrijaperovic** [comment]
> Thanks for the contribution, can you also add an else block which tells user that they need to set those params if not found?

@jainr i believe these are already standard feast Azure environment variables. They are referenced in the historical features python notebook.

**Comment by jainr** [comment]
Looks good, approving it.

**Pull request merged**
