### PR TITLE
Adding local helm chart and changing install script

### PR DESCRIPTION
**Pull request by jainr**
Adding helm chart and changing script, so feast can be installed from local helm chart that contains the updates rbac apis thats compatible with latest versions of Kubernetes.

This PR solves the issue where the older rbac v1beta apis are not compatible with latest Kubernetes version.
This fixes that problem but the chart needs to be installed from local feast-0.9.5-helmchart folder.

### CODE REVIEW

**Comment by jainr** [comment]
@snowmanmsft

**Comment by andrijaperovic** [comment]
This is how I was able to also install the helm chart on AKS `v1.22`.

However, I think (I may be wrong) that the crux of the problem is the fact that `feast-azure-provider` is not compatible with newest versions of `feast` which might also be correlated to the fact that `feast-spark` depends on feast v0.9:
https://github.com/Azure/feast-azure/issues/40

Unless there is a plan to somehow stage this helm chart internally @ Microsoft (e.g. central helm repository), this is probably the only viable short-term fix.

**Comment by cbtham** [comment]
> This is how I was able to also install the helm chart on AKS `v1.22`.
> 
> However, I think (I may be wrong) that the crux of the problem is the fact that `feast-azure-provider` is not compatible with newest versions of `feast` which might also be correlated to the fact that `feast-spark` depends on feast v0.9: #40
> 
> Unless there is a plan to somehow stage this helm chart internally @ Microsoft (e.g. central helm repository), this is probably the only viable short-term fix.

feast-azure-provider will not work with any version other than 0.15.1 at the moment

**Comment by adchia** [comment]
There weren't any breaking changes for this provider between 0.15.1 and 0.17/0.18, so should be as simple as doing feast[redis] >= 0.15.1

**Pull request merged**
